env:
  GATEWAY_DEBUG: true
  GRPC_AUTH_ADDRESS: "ch-auth"
  GRPC_AUTH_PORT: "1112"
  CONFIG_FILE: "config.toml"
  ROUTES_FILE: "/routes/routes.toml"
  TLS_CERT: "/cert/tls.crt"
  TLS_KEY: "/cert/tls.key"
