stages:
  - deploy


variables:
  CONTAINER_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}
  NAMESPACE: hosting


deploy sandbox:
  image: exon/helm
  stage: deploy
  tags:
    - develop
  before_script:
    - mkdir -p /etc/deploy/
    - echo ${SANDBOX_KUBE_CONFIG} | base64 -d > ${KUBECONFIG}
    - helm init --client-only
    - helm repo update
  environment:
    name: develop
  script:
    - cd deploy
    - helm upgrade --install ${CI_PROJECT_NAME} --debug --namespace=${NAMESPACE} --set image.tag="develop-55ced2a80678bc484a30e802acc4450905b7f968" --values values.yaml --values env/develop.yaml .
