sudo: required

language: go

env:
  global:
  - OWNER=containerum
  - NAME=api-gateway
  - IMAGE_NAME=$OWNER/gateway
  - HELM_URL=https://$OWNER.github.io/gateway/charts

services:
  - docker

install:
  - curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash
  - helm init --client-only
  - helm plugin install https://github.com/chartmuseum/helm-push
  - go get github.com/mikefarah/yq
  - sudo apt-get install jq

script:
  - docker build -t "$IMAGE_NAME" .

before_deploy:
  - docker login -u="$DOCKER_LOGIN" -p="$DOCKER_PASSWORD"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${TRAVIS_TAG}"
  - yq write --inplace charts/api-gateway/values.yaml image.tag "${TRAVIS_TAG}"
  - helm package charts/$NAME --version="${TRAVIS_TAG}" --dependency-update --destination charts
  - helm repo add chartmuseum https://charts.containerum.io

deploy:
  - provider: script
    script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${TRAVIS_TAG}"
    on:
      tags: true
  - provider: script
    script: helm push -u ${HELM_USER} -p ${HELM_PASSWORD} charts/$NAME chartmuseum
    on:
      tags: true
  - provider: releases
    api_key: $GITHUB_TOKEN
    file:
      - "charts/$NAME-${TRAVIS_TAG}.tgz"
      - "charts/index.yaml"
    skip_cleanup: true
    on:
      tags: true
