---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: "ch-gateway"
    access: "true"
    group: local
  name: ch-gateway
  namespace: hosting
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: "ch-gateway"
      access: "true"
      group: local
  template:
    metadata:
      labels:
        app: "ch-gateway"
        access: "true"
        group: local
    spec:
      containers:
      - image: ${IMAGE}
        name: ch-gateway
        env:
        - name: PG_USER
          value: '${${ZONE}_PG_USER}'
        - name: PG_PASSWORD
          value: '${${ZONE}_PG_PASSWORD}'
        - name: PG_DATABASE
          value: '${${ZONE}_PG_DATABASE}'
        - name: PG_ADDRESS
          value: '${${ZONE}_PG_ADDRESS}'
        - name: PG_PORT
          value: '${${ZONE}_PG_PORT}'
        - name: PG_DEBUG
          value: '${${ZONE}_PG_DEBUG}'
        - name: STATSD_ADDRESS
          value: '${${ZONE}_STATSD_ADDRESS}'
        - name: REDIS_ADDRESS
          value: '${${ZONE}_REDIS_ADDRESS}'
        - name: STATSD_PREFIX
          value: '${${ZONE}_STATSD_PREFIX}'
        - name: STATSD_BUFFER_TIME
          value: '${${ZONE}_STATSD_BUFFER_TIME}'
        - name: GATEWAY_DEBUG
          value: '${${ZONE}_GATEWAY_DEBUG}'
        - name: GRPC_AUTH_ADDRESS
          value: '${${ZONE}_GRPC_AUTH_ADDRESS}'
        - name: GRPC_AUTH_PORT
          value: '${${ZONE}_GRPC_AUTH_PORT}'
        - name: CLICKHOUSE_LOGGER
          value: '${${ZONE}_CLICKHOUSE_LOGGER}'
        volumeMounts:
        - mountPath: /cert/
          name: config
      imagePullSecrets:
      - name: regsecret
      volumes:
        - name: config
          configMap:
            name: ch-gateway
