[prune]
    non-go = true
    go-tests = true
    unused-packages = true

    [[prune.project]]
      name = "github.com/containerum/cherry"
      non-go = false

    [[prune.project]]
      name = "github.com/containerum/kube-client"
      non-go = false

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.1.0"

[[constraint]]
  branch = "develop"
  name = "git.containerum.net/ch/auth"

[[constraint]]
  name = "github.com/containerum/cherry"
  version = "~1.0.1"

[[constraint]]
  name = "github.com/containerum/utils"
  version = "~1.0.0"