[routes.ingress_create]
active = true
name = "Create Ingress"
method = "POST"
roles = ["*"]
upstream = "http://resource-service:1213"
listen = "/namespaces/:namespace/ingresses"
strip = false
group = "resource-service"

[routes.ingress_delete]
active = true
name = "Delete Ingress"
method = "DELETE"
roles = ["*"]
upstream = "http://resource-service:1213"
listen = "/namespaces/:namespace/ingresses/:ingress"
strip = false
group = "resource-service"

[routes.ingress_update]
active = true
name = "Update Ingress"
method = "PUT"
roles = ["*"]
upstream = "http://resource-service:1213"
listen = "/namespaces/:namespace/ingresses/:ingress"
strip = false
group = "resource-service"

[routes.resources_count_get]
active = true
name = "Get Resources Count"
method = "GET"
roles = ["*"]
upstream = "http://resource-service:1213"
listen = "/resources"
strip = false
group = "resource-service"

[routes.deployment_create]
active = true
name = "Create Deployment"
method = "POST"
roles = ["*"]
upstream = "http://resource-service:1213"
listen = "/namespaces/:namespace/deployments"
strip = false
group = "resource-service"

[routes.deployment_replace]
active = true
name = "Replace Deployment"
method = "PUT"
roles = ["*"]
upstream = "http://resource-service:1213"
listen = "/namespaces/:namespace/deployments/:deployment"
strip = false
group = "resource-service"

[routes.deployment_delete]
active = true
name = "Delete Deployment"
method = "DELETE"
roles = ["*"]
upstream = "http://resource-service:1213"
listen = "/namespaces/:namespace/deployments/:deployment"
strip = false
group = "resource-service"

[routes.service_create]
active = true
name = "Create Service"
method = "POST"
roles = ["*"]
upstream = "http://resource-service:1213"
listen = "/namespaces/:namespace/services"
strip = false
group = "resource-service"

[routes.service_replace]
active = true
name = "Replace Service"
method = "PUT"
roles = ["*"]
upstream = "http://resource-service:1213"
listen = "/namespaces/:namespace/services/:service"
strip = false
group = "resource-service"

[routes.service_delete]
active = true
name = "Delete Service"
method = "DELETE"
roles = ["*"]
upstream = "http://resource-service:1213"
listen = "/namespaces/:namespace/services/:service"
strip = false
group = "resource-service"
