[routes.import_all_events]
active = true
name = "Get all events for all resources"
method = "GET"
roles = ["*"]
upstream = "http://events-api:1667"
listen = "/events/all"
strip = false
group = "events-api"
ws = true

[routes.import_selected_events]
active = true
name = "Get selected events for all resources"
method = "GET"
roles = ["*"]
upstream = "http://events-api:1667"
listen = "/events/selected"
strip = false
group = "events-api"
ws = true

[routes.import_all_namespace_events]
active = true
name = "Get all events for namespace"
method = "GET"
roles = ["*"]
upstream = "http://events-api:1667"
listen = "/events/namespaces/:namespace/all"
strip = false
group = "events-api"
ws = true

[routes.import_selected_namespace_events]
active = true
name = "Get selected events for namespace"
method = "GET"
roles = ["*"]
upstream = "http://events-api:1667"
listen = "/events/namespaces/:namespace/selected"
strip = false
group = "events-api"
ws = true

[routes.get_events_by_page]
active = true
name = "Get events by page"
method = "GET"
roles = ["*"]
upstream = "http://events-api:1667"
listen = "/events/"
strip = false
group = "events-api"
