[routes.import_all]
active = true
name = "Import all resources"
method = "POST"
roles = ["admin"]
upstream = "http://kube-events:5555"
listen = "/all"
strip = false
group = "kube-events"

[routes.import_all_ws]
active = true
name = "Import all resources ws"
method = "GET"
roles = ["admin"]
upstream = "http://kube-events:5555"
listen = "/all/ws"
strip = false
group = "kube-events"
ws = true
