[routes.current_memory]
active = true
name = "Get current memory"
method = "GET"
roles = ["*"]
upstream = "http://nodemetrics:8090"
listen = "/memory/current"
strip = false
group = "nodemetrics"

[routes.history_memory]
active = true
name = "Get history memory"
method = "GET"
roles = ["*"]
upstream = "http://nodemetrics:8090"
listen = "/memory/history"
strip = false
group = "nodemetrics"

[routes.history_memory_node]
active = true
name = "Get history memory by node"
method = "GET"
roles = ["*"]
upstream = "http://nodemetrics:8090"
listen = "/memory/history/nodes"
strip = false
group = "nodemetrics"

[routes.history_memory_ws]
active = true
name = "Get history memory websockets"
method = "GET"
roles = ["*"]
upstream = "http://nodemetrics:8090"
listen = "/memory/history/ws"
strip = false
group = "nodemetrics"

[routes.history_memory_node_ws]
active = true
name = "Get history memory by node websockets"
method = "GET"
roles = ["*"]
upstream = "http://nodemetrics:8090"
listen = "/memory/history/nodes/ws"
strip = false
group = "nodemetrics"

[routes.current_cpu]
active = true
name = "Get current cpu"
method = "GET"
roles = ["*"]
upstream = "http://nodemetrics:8090"
listen = "/cpu/current"
strip = false
group = "nodemetrics"

[routes.history_cpu]
active = true
name = "Get history cpu"
method = "GET"
roles = ["*"]
upstream = "http://nodemetrics:8090"
listen = "/cpu/history"
strip = false
group = "nodemetrics"

[routes.history_cpu_node]
active = true
name = "Get history cpu by node"
method = "GET"
roles = ["*"]
upstream = "http://nodemetrics:8090"
listen = "/cpu/history/nodes"
strip = false
group = "nodemetrics"

[routes.history_cpu_ws]
active = true
name = "Get history cpu websocket"
method = "GET"
roles = ["*"]
upstream = "http://nodemetrics:8090"
listen = "/cpu/history/ws"
strip = false
group = "nodemetrics"

[routes.history_cpu_node_ws]
active = true
name = "Get history cpu by node websocket"
method = "GET"
roles = ["*"]
upstream = "http://nodemetrics:8090"
listen = "/cpu/history/nodes/ws"
strip = false
group = "nodemetrics"

[routes.current_storage]
active = true
name = "Get current storage"
method = "GET"
roles = ["*"]
upstream = "http://nodemetrics:8090"
listen = "/storage/current"
strip = false
group = "nodemetrics"
