[routes.templates_get]
active = true
name = "Get Solution Templates"
method = "GET"
roles = ["*"]
upstream = "http://solutions:4343"
listen = "/templates"
strip = false
group = "solutions"

[routes.template_env_get]
active = true
name = "Get Solution Template Env"
method = "GET"
roles = ["*"]
upstream = "http://solutions:4343"
listen = "/templates/:template/env"
strip = false
group = "solutions"

[routes.solutions_get]
active = true
name = "Get Solutions"
method = "GET"
roles = ["*"]
upstream = "http://solutions:4343"
listen = "/solutions"
strip = false
group = "solutions"

[routes.solutions_run]
active = true
name = "Run Solutions"
method = "POST"
roles = ["*"]
upstream = "http://solutions:4343"
listen = "/solutions"
strip = false
group = "solutions"

[routes.solution_deployments_get]
active = true
name = "Get Solution Deployments"
method = "GET"
roles = ["*"]
upstream = "http://solutions:4343"
listen = "/solutions/:solution/deployments"
strip = false
group = "solutions"

[routes.solution_services_get]
active = true
name = "Get Solution Services"
method = "GET"
roles = ["*"]
upstream = "http://solutions:4343"
listen = "/solutions/:solution/services"
strip = false
group = "solutions"

[routes.solution_delete]
active = true
name = "Delete Solution"
method = "DELETE"
roles = ["*"]
upstream = "http://solutions:4343"
listen = "/solutions/:solution"
strip = false
group = "solutions"