apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "name" . }}-{{ .Values.name }}"
data:
  {{ range $k, $v := .Values.routes }}
  {{ $v.name }} : |-
{{ $.Files.Get $v.path | indent 4 }}
  {{ end }}
