apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ template "name" . }}-{{ .Values.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  externalIPs:
  - {{ .Values.service.externalIP }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      name: {{ .Values.service.name }}
    - port: 443
      targetPort: {{ .Values.service.internalPort }}
      name: {{ .Values.service.name }}-https
  selector:
    app: {{ template "name" . }}-{{ .Values.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
