replicaCount: 1
strategy:
  type: RollingUpdate
  maxSurge: 1
  maxUnavailable: 1

name: api-gateway

image:
  secret: gitlab-registry
  repository: registry.containerum.net/ch/api-gateway
  tag: latest
  pullPolicy: Always

service:
  name: api-gateway
  externalPort: 8082
  externalIP: 192.168.88.210
  internalPort: 8082

resources: {}

routes:
  path: "env/routes/routes.toml"
