replicaCount: 1
strategy:
  type: RollingUpdate
  maxSurge: 1
  maxUnavailable: 1

name: api-gateway-test

image:
  secret: gitlab-registry
  repository: registry.containerum.net/ch/api-gateway
  tag: latest
  pullPolicy: Always

service:
  name: api-gateway-test
  externalPort: 8087
  externalIP: 192.168.88.210
  internalPort: 8087

resources: {}

routes:
  - name: routes.toml
    path: "env/routes/routes.toml"
  - name: auth
    path: "env/routes/auth.toml"
  - name: kube
    path: "env/routes/kube.toml"
  - name: resource
    path: "env/routes/resource.toml"
  - name: user
    path: "env/routes/user.toml"
  - name: bill
    path: "env/routes/bill.toml"

config: "env/config.toml"
