---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-routes
  labels:
    app: {{ template "name" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{ range $k, $v := .Values.routes }}
  {{ $v.name }} : |-
{{ $.Files.Get $v.path | indent 4 }}
  {{ end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-config
  labels:
    app: {{ template "name" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": pre-install
data:
  config.toml : |-
    port = 8082

    [tls]
    {{ if .Values.tls.enable }}enable = true
    {{ else }}enable = false{{ end }}

    [healthcheck]
    urls = [
      "http://auth:1111/status",
      "http://kube:1214/status",
      "http://mail:7070/status",
      "http://nodemetrics:8090/status",
      "http://permissions:4242/status",
      "http://resource:1213/status",
      "http://solutions:6767/status",
      "http://user-manager:8111/status",
      "http://volume:4343/status",
      "http://kube-importer:1666/status"
    ]

    [auth]
    enable = true

    [prometheus]
    enable = true
    port = 8282

    [rate]
    enable = true
    limit = 10
    type = "local"
