---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-routes
  labels:
    app: {{ template "name" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{ range $k, $v := .Values.routes }}
  {{ $v.name }} : |-
{{ $.Files.Get $v.path | indent 4 }}
  {{ end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-config
  labels:
    app: {{ template "name" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": pre-install, post-delete
data:
  config.toml : |-
{{ $.Files.Get .Values.config | indent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-cert
  labels:
    app: {{ template "name" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": pre-install, post-delete
data:
  tls.crt: |
    Certificate
  tls.key: |
    Certificate Key
