{{ if .Values.tls.enable }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": pre-install,post-delete
type: Opaque
data:
  tls.crt:
    {{ .Values.tls.cert  }}
  tls.key:
    {{ .Values.tls.key }}
{{ end }}
